AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus - quarkus-amazon-lambda-common-deployment
Globals:
  Api:
    BinaryMediaTypes:
    - '*/*'
Resources:
  DecisiontableQuarkusExampleFinalNative:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: s3://com.sjfisher.lam/6c528fac7b938d208ef8485d6b49c604
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
    Metadata:
      SamResourceId: DecisiontableQuarkusExampleFinalNative
